CB-2647 top bar menu redesign
dbeaver/cloudbeaver pull request #1257
Opened 2022-11-02 18:23 UTC by Wroud

2022-11-04 13:15 UTC, devnaumov requested changes

2022-11-04 13:15 UTC, devnaumov commented on webapp/packages/plugin-log-viewer/src/LocaleService.ts
> +/*
Please change licence text

2022-11-04 13:15 UTC, devnaumov commented on webapp/packages/plugin-sql-editor-navigation-tab/src/LocaleService.ts
> +/*
please change the licence text

2022-11-04 13:15 UTC, devnaumov commented on webapp/packages/plugin-tools-panel/src/LocaleService.ts
> +/*
please change license text

2022-11-04 13:15 UTC, devnaumov commented on webapp/packages/plugin-top-app-bar/src/TopNavBar/shared/topMenuStyles.ts
> +    clip-path: inset(0px -16px -16px -16px);
please leave a comment that explains what it does

2022-11-07 17:09 UTC, Wroud commented on webapp/packages/plugin-log-viewer/src/LocaleService.ts
> +/*
fixed

2022-11-07 17:09 UTC, Wroud commented on webapp/packages/plugin-sql-editor-navigation-tab/src/LocaleService.ts
> +/*
fixed

2022-11-07 17:10 UTC, Wroud commented on webapp/packages/plugin-tools-panel/src/LocaleService.ts
> +/*
fixed

2022-11-07 17:10 UTC, Wroud commented on webapp/packages/plugin-top-app-bar/src/TopNavBar/shared/topMenuStyles.ts
> +    clip-path: inset(0px -16px -16px -16px);
fixed

2022-11-07 19:46 UTC, devnaumov approved these changes

2022-11-09 08:24 UTC, merged