CB-3073 add ddl resource, remove ddl controller
dbeaver/cloudbeaver pull request #1563
Opened 2023-03-23 13:39 UTC by tfokina

2023-03-23 13:57 UTC, Wroud requested changes

2023-03-23 13:57 UTC, Wroud commented on webapp/packages/plugin-ddl-viewer/src/DdlViewer/DDLViewerTabPanel.tsx
> +    <Loader state={[ddlResource, connectionDialectResource]}>
Loader now can be skipped (Suspense)

2023-03-23 13:57 UTC, Wroud commented on webapp/packages/plugin-ddl-viewer/src/DdlViewer/DdlResource.ts
> +export class DdlResource extends CachedMapResource<string, string> {
great job!

2023-03-23 13:57 UTC, Wroud commented on webapp/packages/plugin-ddl-viewer/src/DdlViewer/DDLViewerTabPanel.tsx
> +  const connection = connectionInfoResource.getConnectionForNode(nodeId);
probably it's better to load active project connections before
```
const connectionInfoResource = useResource(DDLViewerTabPanel, ConnectionInfoResource, ConnectionInfoActiveProjectKey);

const connection = connectionInfoResource.resource.getConnectionForNode(nodeId);
```

2023-03-23 14:35 UTC, tfokina commented on webapp/packages/plugin-ddl-viewer/src/DdlViewer/DDLViewerTabPanel.tsx
> +  const connection = connectionInfoResource.getConnectionForNode(nodeId);
Done

2023-03-23 14:36 UTC, tfokina commented on webapp/packages/plugin-ddl-viewer/src/DdlViewer/DDLViewerTabPanel.tsx
> +    <Loader state={[ddlResource, connectionDialectResource]}>
Fixed

2023-03-24 03:35 UTC, Wroud approved these changes

2023-03-28 10:56 UTC, merged