CB-3163 text overflow in header
dbeaver/cloudbeaver pull request #1595
Opened 2023-04-07 08:48 UTC by tfokina

2023-04-07 11:57 UTC, Wroud requested changes

2023-04-07 11:57 UTC, Wroud commented on webapp/packages/plugin-authentication-administration/src/Administration/IdentityProviders/AuthConfigurationsTable/AuthConfigurationsTable.tsx
> +      max-height: calc(100vh - 152px); /* size for height overflow */
we can't relay to constant size with `152px`, we need another approach

2023-04-14 14:08 UTC, tfokina commented on webapp/packages/plugin-authentication-administration/src/Administration/IdentityProviders/AuthConfigurationsTable/AuthConfigurationsTable.tsx
> +      max-height: calc(100vh - 152px); /* size for height overflow */
Removed this

2023-04-14 14:14 UTC, Wroud approved these changes

2023-04-14 14:14 UTC, Wroud commented on webapp/packages/plugin-authentication-administration/src/Administration/Users/Teams/TeamsTable/TeamsTable.tsx
> +  return styled(useStyles(BASE_CONTAINERS_STYLES))(
does we need `BASE_CONTAINERS_STYLES`? we don't use container components here

2023-04-14 14:29 UTC, tfokina commented on webapp/packages/plugin-authentication-administration/src/Administration/Users/Teams/TeamsTable/TeamsTable.tsx
> +  return styled(useStyles(BASE_CONTAINERS_STYLES))(
Removed unnecessary styles

2023-04-18 11:57 UTC, merged