CB-3303-edit-driver-settings
dbeaver/cloudbeaver pull request #1607
Opened 2023-04-13 16:33 UTC by yagudin10

2023-04-18 14:45 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/model/user/WebDataSourceDescriptorInfo.java
> +
add id

2023-04-19 13:15 UTC, tfokina approved these changes

2023-04-19 13:15 UTC, tfokina commented on webapp/packages/core-blocks/src/FormControls/InputFiles.tsx
> +            {translate(rest.multiple ? 'ui_upload_files' : 'ui_upload_file')}
maybe extract `multiple` from `rest` and just use `multiple`?

2023-05-10 14:14 UTC, Wroud requested changes

2023-05-10 14:14 UTC, Wroud commented on webapp/packages/core-connections/src/DBDriverResource.ts
> +        includeProviderProperties: false,
```suggestion
        ...this.getDefaultIncludes(),
        ...this.getIncludesMap(config.id),
```

2023-05-10 14:14 UTC, Wroud commented on webapp/packages/core-connections/src/DBDriverResource.ts
> +      includeProviderProperties: false,
```suggestion
      ...this.getDefaultIncludes(),
```

2023-05-10 14:14 UTC, Wroud commented on webapp/packages/core-connections/src/DBDriverResource.ts
> +      }
delete must be done in performUpdate, performUpdate is like transaction that must provide final state.

why: because we don't want to allow transactions that can deal with deleted objects (or outdated) between request to delete on backend and deletion in UI

2023-05-11 12:19 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputFiles.tsx
> +            {translate(rest.multiple ? 'ui_upload_files' : 'ui_upload_file')}
we can, but then we need to pass `multiple` prop to `UploadArea` also

2023-05-11 12:30 UTC, Wroud requested changes

2023-05-11 12:30 UTC, Wroud commented on webapp/packages/core-connections/src/DBDriverResource.ts
> +  async editDriver(config: DriverConfig): Promise<DBDriver> {
`updateDriver`

2023-05-11 12:33 UTC, Wroud requested changes

2023-05-11 12:33 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputFiles.tsx
> +import { Button, Tag, Tags, useCombinedHandler } from '..';
don't import from index file (it's can make circular dependency and broke the build)

2023-05-16 21:49 UTC, Wroud approved these changes

2023-05-16 21:49 UTC, Wroud approved these changes

2023-05-17 10:42 UTC, merged