CB-3616 add logs for local rm
dbeaver/cloudbeaver pull request #1839
Opened 2023-07-24 10:24 UTC by yagudin10

2023-07-24 11:44 UTC, alexander-skoblikov reviewed
Add information about who change data

2023-07-24 15:10 UTC, serge-rider requested changes

2023-07-24 15:10 UTC, serge-rider commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/model/rm/local/LocalResourceController.java
> +                log.debug("Updating value for property '" + propName + "'");
Provide more info (at least project ID)

2023-07-24 15:10 UTC, serge-rider commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/model/rm/local/LocalResourceController.java
> +                        log.debug("Deleting data source '" + dataSourceId + "'");
Also add project info here and all project-related functions

2023-07-26 08:19 UTC, serge-rider approved these changes

2023-07-27 15:16 UTC, merged