CB-3769-user-role-change-event
dbeaver/cloudbeaver pull request #1880
Opened 2023-08-07 16:18 UTC by yagudin10

2023-08-09 14:34 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/model/session/BaseWebSession.java
> +        } catch (DBException e) {
we also should refresh permissions

2023-08-09 14:36 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/model/session/WebUserContext.java
> +    public void refreshAccessibleProjects() throws DBException {
synchronized

2023-08-15 14:24 UTC, Wroud approved these changes

2023-08-15 14:24 UTC, Wroud commented on webapp/packages/core-localization/src/locales/ru.ts
> +  ['app_root_event_permissions_changed_message', 'Ваши настройки доступа были изменены'],
`Ваши права доступа были изменены`

2023-08-15 15:06 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/model/session/WebUserContext.java
> +        this.securityController = application.createSecurityController(this);
we should not recreate clients

2023-08-15 15:09 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/events/WSSubjectPermissionUpdatedEventHandler.java
> +        var user = activeUserSession.getUserContext().getUser();
use subject type from event

2023-08-15 15:32 UTC, alexander-skoblikov approved these changes

2023-08-16 09:21 UTC, Wroud requested changes

2023-08-16 09:21 UTC, Wroud commented on webapp/packages/core-root/src/SessionPermissionsResource.ts
> +          .requestSynchronization('permissions', this.localizationService.translate('app_root_event_permissions_changed_message'))
probably you can't use core-localization here (circular dependency between packages)

2023-08-16 12:11 UTC, Wroud requested changes

2023-08-16 12:11 UTC, Wroud commented on webapp/packages/plugin-root/src/DataSynchronization/DataSynchronizationNotification.tsx
> +              return <div key={messages[0].label}>{translate(message)}</div>;
probably you need to translate every message in messages in map function

2023-08-16 12:17 UTC, Wroud approved these changes

2023-08-16 12:19 UTC, merged