CB-3778-bug-use-oracle-as-internal-db
dbeaver/cloudbeaver pull request #1920
Opened 2023-08-16 13:26 UTC by yagudin10

2023-08-22 12:30 UTC, serge-rider requested changes

2023-08-22 12:30 UTC, serge-rider commented on server/bundles/io.cloudbeaver.service.security/src/io/cloudbeaver/service/security/db/CBDatabase.java
> +        DBPPreferenceStore prefStore = SQLQueryTranslator.getDefaultPreferenceStore();
Why we translate non-DDL queries?
It is really slow and also we shouldn't use non-standard SQL in select/update/delete.

2023-08-22 12:33 UTC, yagudin10 commented on server/bundles/io.cloudbeaver.service.security/src/io/cloudbeaver/service/security/db/CBDatabase.java
> +        DBPPreferenceStore prefStore = SQLQueryTranslator.getDefaultPreferenceStore();
Because for some cases we can't use our scripts from SM controller (f.e. Oracle and SQL Server don't support offset and limit)

2023-10-30 16:59 UTC, serge-rider approved these changes

2023-10-30 16:59 UTC, merged