Cb 4198 gcp file system support
dbeaver/cloudbeaver pull request #2115
Opened 2023-11-09 11:14 UTC by yagudin10

2023-11-09 11:35 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.fs/src/io/cloudbeaver/service/fs/WebFSUtils.java
> +public class WebFSUtils {
use FSUtils

2023-11-09 11:55 UTC, alexander-skoblikov requested changes

2023-11-09 11:55 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.fs/src/io/cloudbeaver/service/fs/impl/WebServiceFS.java
> +            parentNode.refreshNode(webSession.getProgressMonitor(), this);
```suggestion
            parentNode.addChildResource(filePath);
            return new FSFile(parentNode.getChild(filePath));
```

2023-11-09 11:55 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.fs/src/io/cloudbeaver/service/fs/impl/WebServiceFS.java
> +            Path to = Files.move(from, parentPath.resolve(fileName));
same here

2023-11-09 11:55 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.fs/src/io/cloudbeaver/service/fs/impl/WebServiceFS.java
> +            dbnPath.refreshNode(webSession.getProgressMonitor(), this);
```suggestion
            dbnPath.removeChildResource(oldpath);
            dbnPath.addChildResource(newPath);```

2023-11-09 11:55 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.fs/src/io/cloudbeaver/service/fs/impl/WebServiceFS.java
> +            parentNode.refreshNode(webSession.getProgressMonitor(), this);
same here

2023-11-10 15:18 UTC, devnaumov approved these changes

2023-11-13 11:17 UTC, alexander-skoblikov approved these changes

2023-11-13 11:18 UTC, merged