CB-4356 useForm does not switch tabs like insane after press enter
dbeaver/cloudbeaver pull request #2211
Opened 2023-12-07 18:15 UTC by sergeyteleshev

2023-12-11 13:11 UTC, Wroud requested changes

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-blocks/src/useExecutor.ts
> +    props.postHandlers,
props.postHandlers need to be removed from dependencies:
we depend only on handlers count in array (handlers wrapped with function that use index from current array)

you can move out of useEffect:
```
    const next: IExecutorHandlersCollection<T> | undefined = props.next;
    const before: IExecutorHandlersCollection<T> | undefined = props.before;
```
and use this constants in the dependencies

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-ui/src/Tabs/TabPanelList.tsx
> +    <TabPanelValidationHandler>
probably will be better to move it to TabsState (so we will be sure that all uses of TabPanel in TabsState have this context)

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandler.tsx
> +      </div>
seems like this div is extra (ref not in use)

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandler.tsx
> +  const selectedTab = state?.state.selectedId;
this `selectedTab` will be captured on first render and then in `useEffect` we will get "old" state (if tabs will be changed)

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandler.tsx
> +  const selectedTab = state?.state.selectedId;
you can read this value in useEffect or add it to effect dependencies

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandler.tsx
> +  }, []);
We can simplify logic:
in each TabPanel notify context when panel is invalid

in this context schedule update when tab notify about validation
now check if selected tab invalid (if so skip tab switching)
else select first invalid tab

after tab switching execute validation again to display browser validation message (optionally we can track exact field to prevent full form validation)

2023-12-11 13:11 UTC, Wroud commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandler.tsx
> +  const value = useMemo(() => ({ addInvalidTab, invalidTabs }), []);
you can use `useObjectRef` for such cases (it returns persist object that can be passed to contexts to prevent re-renders while fields of object mutated on every render)

2023-12-11 16:50 UTC, devnaumov submitted a review, later dismissed

2023-12-11 16:50 UTC, devnaumov commented on webapp/packages/core-ui/src/Tabs/TabPanel.tsx
> +    panelRef.current?.removeEventListener('invalid', trackValidity, true);
Extra one? Seems like we remove listener in the useEffect callback function

2023-12-11 16:50 UTC, devnaumov commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandler.tsx
> +import { observer } from 'mobx-react-lite';
please add license text

2023-12-11 16:50 UTC, devnaumov commented on webapp/packages/core-ui/src/Tabs/TabPanelValidationHandlerContext.ts
> +import { MutableRefObject, createContext } from 'react';
please add license text

2023-12-13 08:44 UTC, Wroud approved these changes

2023-12-18 12:03 UTC, merged