CB-4289 add file name param for data export
dbeaver/cloudbeaver pull request #2308
Opened 2024-01-18 10:34 UTC by yagudin10

2024-01-19 15:07 UTC, Wroud requested changes

2024-01-19 15:07 UTC, Wroud commented on webapp/packages/plugin-data-export/src/ACTION_EXPORT_DATA.ts
> +});
why not to use ACTION_EXPORT? (it's exists already)

2024-01-19 15:07 UTC, Wroud commented on webapp/packages/core-utils/src/withTimestamp.ts
> +}
what difference with `generateFileName`? 
should we remove one of them?

2024-01-19 15:43 UTC, Wroud approved these changes

2024-01-22 11:25 UTC, sergeyteleshev approved these changes

2024-01-22 15:30 UTC, merged