CB-4651 change wrap lines icons
dbeaver/cloudbeaver pull request #2371
Opened 2024-02-08 21:28 UTC by devnaumov

2024-02-09 09:48 UTC, Wroud requested changes

2024-02-09 09:48 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/ValuePanelPresentation/TextValue/TextValuePresentation.tsx
> +            name={lineWrapping ? 'unwrap-lines' : 'wrap-lines'}
please don't extend icons.svg anymore, place different size icons into plugin-data-viewer/public/icons/
name like:
`plugin_data_viewer_wrap_lines(|_sm|_m)`
`plugin_data_viewer_no_wrap_lines(|_sm|_m)`

example:
32px - `plugin_data_viewer_wrap_lines.svg`
24px - `plugin_data_viewer_wrap_lines_m.svg`
16px - `plugin_data_viewer_wrap_lines_sm.svg`

2024-02-09 16:33 UTC, Wroud approved these changes

2024-02-12 07:50 UTC, Wroud approved these changes

2024-02-12 09:21 UTC, sergeyteleshev approved these changes

2024-02-12 10:06 UTC, merged