CB-4700 allow administrators to copy data
dbeaver/cloudbeaver pull request #2389
Opened 2024-02-16 13:10 UTC by devnaumov

2024-02-19 09:54 UTC, sergeyteleshev approved these changes

2024-02-21 14:46 UTC, Wroud requested changes

2024-02-21 14:46 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/DataViewerService.ts
> +    return !connection.readOnly;
something is not right (connection.readOnly must be joined condition)

2024-02-21 15:16 UTC, Wroud approved these changes

2024-02-26 13:38 UTC, merged