CB-4884 migrate sql editor to css modules
dbeaver/cloudbeaver pull request #2487
Opened 2024-03-20 23:49 UTC by devnaumov

2024-03-21 11:05 UTC, sergeyteleshev commented
please also remove this file it is not in use
+ delete reshadow from package.json

![image](https://github.com/dbeaver/cloudbeaver/assets/26230285/78723f9d-574d-4785-b308-c8613771bbfc)

2024-03-21 11:05 UTC, sergeyteleshev approved these changes

2024-03-21 11:28 UTC, Wroud requested changes

2024-03-21 11:28 UTC, Wroud commented on webapp/packages/plugin-sql-editor/src/SqlEditorStatusBar.m.css
> +.loader {
please add license to all .m.css files

2024-03-21 19:32 UTC, sergeyteleshev approved these changes

2024-03-22 04:36 UTC, Wroud approved these changes

2024-03-22 04:37 UTC, merged