CB-4074 transform metadata editor footer to the new context menu
dbeaver/cloudbeaver pull request #2490
Opened 2024-03-21 15:41 UTC by devnaumov

2024-03-22 04:47 UTC, Wroud requested changes

2024-03-22 04:47 UTC, Wroud commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/MENU_OBJECT_VIEWER_FOOTER_ACTIONS.ts
> +export const MENU_OBJECT_VIEWER_FOOTER_ACTIONS = createMenu('object-viewer-footer-actions', 'Object viewer footer actions menu');
please don't use `MENU` and `ACTIONS` in the same name because we use this key words for splitting menus and actions globally

2024-03-22 04:47 UTC, Wroud commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/DATA_CONTEXT_OBJECT_VIEWER_TABLE_STATE.ts
> +export const DATA_CONTEXT_OBJECT_VIEWER_TABLE_STATE = createDataContext<TableState>('object-viewer-table-state');
please remove, you using only `selectedList` from this object

2024-03-22 04:47 UTC, Wroud commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/DATA_CONTEXT_OBJECT_VIEWER_NODES.ts
> +export const DATA_CONTEXT_OBJECT_VIEWER_NODES = createDataContext<string[]>('object-viewer-nodes');
seems like you don't use this context

2024-03-22 04:47 UTC, Wroud commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/ObjectPropertyTableFooter.tsx
> +  menu.context.set(DATA_CONTEXT_OBJECT_VIEWER_TABLE_STATE, tableState);
i will suggest to use `DATA_CONTEXT_NAV_NODE` and `DATA_CONTEXT_NAV_NODES`
https://github.com/dbeaver/cloudbeaver/blob/f8a36c09ee11eba183b852cf70832f5b1f696ecf/webapp/packages/plugin-navigation-tree/src/NavigationTree/ElementsTree/NavigationTreeNode/NavigationNode.tsx#L67-L69

2024-03-22 17:53 UTC, Wroud approved these changes

2024-03-25 13:02 UTC, sergeyteleshev approved these changes

2024-03-25 15:07 UTC, merged