Cb 4629 end user preferences
dbeaver/cloudbeaver pull request #2546
Opened 2024-04-11 15:40 UTC by alexander-skoblikov

2024-04-11 16:17 UTC, devnaumov approved these changes

2024-04-12 10:57 UTC, yagudin10 approved these changes

2024-04-12 10:57 UTC, yagudin10 commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/WebProjectImpl.java
> +        DBPPreferenceStore preferenceStore
add annotation

2024-04-12 12:33 UTC, sergeyteleshev requested changes

2024-04-12 12:33 UTC, sergeyteleshev commented on webapp/packages/plugin-user-profile-settings/src/UserProfileSettings.tsx
> +            <ToolsAction icon="admin-cancel" viewBox="0 0 24 24" onClick={handleRestoreDefaults}>
I dont like we have 2 similar icons. This is misleading the user

2024-04-12 12:33 UTC, sergeyteleshev commented on webapp/packages/plugin-user-profile-settings/src/UserProfileSettings.tsx
> +    userSettingsService.restoreDefaults();
Usually restore settings goes this scenario:
1. press restore settings
2. popup "are you sure you want to restore settings"
3. click yes/no
4. settings applies

Since we have another pipline here, which is fine, by the way. I believe we should add here some kind of notification here that we pasted here default settings but did not save it yet.

Cuase for example: user had first 5 setttings as default. All settings below visible window area were different from default. You clicked this button and user did not see that something were changed. We need to cover this case so user would not have been missleaded. Generally we need to notify somehow that we pasted something successfully

Or we can go always go first scenario

2024-04-12 12:33 UTC, sergeyteleshev commented on webapp/packages/core-view/src/Menu/MenuService.ts
> +    handlers: for (const handler of this.handlers.values()) {
seems like this logic duplicates in handlig actions and bindings. I beleive we can unify it in function with this cycle. but may be it is not a bad idea to leave it as it is for flexibility reasons

2024-04-12 13:30 UTC, sergeyteleshev approved these changes

2024-04-12 15:15 UTC, devnaumov approved these changes

2024-04-16 15:11 UTC, Wroud commented on webapp/packages/plugin-user-profile-settings/src/UserProfileSettings.tsx
> +            <ToolsAction icon="admin-cancel" viewBox="0 0 24 24" onClick={handleRestoreDefaults}>
fixed

2024-04-16 17:25 UTC, merged