CB-5033 remove reshadow from log viewer and other packages
dbeaver/cloudbeaver pull request #2561
Opened 2024-04-18 19:59 UTC by devnaumov

2024-04-19 10:37 UTC, sergeyteleshev requested changes

2024-04-19 10:37 UTC, sergeyteleshev commented on webapp/packages/core-utils/src/getProgressPercent.test.ts
> +    expect(getProgressPercent(110, 100)).toBe(100);
i dont like that we dont validate anywhere that first argument (done) cause we trust backend here 100% and cannot track a bug once it appeared here
and with current helper implementation we like close the eyes on it and make candy out of its invalid data came with event

2024-04-19 10:37 UTC, sergeyteleshev commented on webapp/packages/core-utils/src/getProgressPercent.test.ts
> +  });
also please add test case with NaN value. cause it is also a number type from typescript perspective of view

2024-04-19 10:37 UTC, sergeyteleshev commented on webapp/packages/core-utils/src/getProgressPercent.test.ts
> +});
plus the second argument (total) also can be tested with all of the test cases you created above for the first one (done). cause something can go wrong here eigther one day

2024-04-19 10:37 UTC, sergeyteleshev commented on webapp/packages/plugin-log-viewer/src/LogViewer/LogEntry.tsx
> +        <Container>{icon && <IconOrImage className={s(styles, { iconOrImage: true })} icon={icon} />}</Container>
feels like container should be with `center` prop

2024-04-19 10:37 UTC, sergeyteleshev commented on webapp/packages/plugin-log-viewer/src/LogViewer/LogEntry.tsx
> +              <Link className={s(styles, { icon: true })} onClick={() => onSelect(item)}>
`link` class here

2024-04-19 10:37 UTC, sergeyteleshev commented on webapp/packages/plugin-resource-manager-scripts/src/ResourceManagerScripts.tsx
> +    <Container vertical>
add `overflow` prop here

2024-04-22 15:19 UTC, Wroud approved these changes

2024-04-22 15:25 UTC, sergeyteleshev approved these changes

2024-04-25 17:25 UTC, merged