CB-5036 disables uploading files for readonly tables for cells
dbeaver/cloudbeaver pull request #2570
Opened 2024-04-23 12:05 UTC by sergeyteleshev

2024-04-23 13:47 UTC, Wroud approved these changes

2024-04-23 13:48 UTC, devnaumov requested changes

2024-04-23 13:48 UTC, devnaumov commented on webapp/packages/plugin-data-spreadsheet-new/src/DataGrid/DataGridContextMenu/DataGridContextMenuSaveContentService.ts
> +        return !format.isBinary(context.data.key) || isReadonlyTable;
just !format.isBinary(context.data.key) || context.data.model.isReadonly(context.data.resultIndex)

2024-04-24 10:05 UTC, devnaumov approved these changes

2024-04-24 10:06 UTC, merged