CB-4980 cancel file upload
dbeaver/cloudbeaver pull request #2573
Opened 2024-04-23 15:54 UTC by devnaumov

2024-04-24 12:59 UTC, sergeyteleshev approved these changes

2024-04-25 10:58 UTC, Wroud requested changes

2024-04-25 10:58 UTC, Wroud commented on webapp/packages/core-sdk/src/CustomGraphQLClient.ts
> +      }
seems like it's better to throw new exception

2024-04-25 10:58 UTC, Wroud commented on webapp/packages/plugin-data-import/src/DataImportService.ts
> +    };
better to have `let cancelImplementation: (() => void) | null = null`
and then set this on every step to proper cancellation function
```
let cancelImplementation: (() => void) | null = null;
function cancel() {
  cancelImplementation?.();
}
```

2024-04-25 10:58 UTC, Wroud commented on webapp/packages/plugin-data-import/src/DataImportService.ts
>        { title: 'plugin_data_import_process_title', message: file.name },
please add notification's `onClose` pointing to`cancel` fn

2024-04-25 12:38 UTC, Wroud commented on webapp/packages/core-blocks/src/Snackbars/ProcessSnackbar.tsx
> +  }
notification can be closed programmatically, because of that, you need to listen for notification close event and invoke the close handler

2024-04-25 12:58 UTC, Wroud approved these changes

2024-04-29 09:16 UTC, merged