CB-4982 disable transaction manager for viewer
dbeaver/cloudbeaver pull request #2576
Opened 2024-04-25 12:30 UTC by devnaumov

2024-04-25 13:43 UTC, Wroud requested changes

2024-04-25 13:43 UTC, Wroud commented on webapp/packages/plugin-datasource-transaction-manager/src/TransactionManagerSettingsService.ts
> +  'plugin.transaction-manager.disabled': schemaExtra.stringedBoolean().default(false),
please use full plugin name `plugin.datasource-transaction-manager.disabled`

2024-04-25 13:43 UTC, Wroud commented on webapp/packages/plugin-datasource-transaction-manager/src/TransactionManagerSettingsService.ts
> +export type TransactionManagerSettingsSchema = typeof defaultSettings;
where do we need this type?
`export type TransactionManagerSettingsSchema = typeof defaultSettings;`

2024-04-25 15:26 UTC, sergeyteleshev approved these changes

2024-04-26 13:49 UTC, Wroud approved these changes

2024-04-26 13:49 UTC, merged