Cb 4460 shared query history for the team
dbeaver/cloudbeaver pull request #2598
Opened 2024-05-08 15:32 UTC by alexander-skoblikov

2024-05-13 09:32 UTC, Wroud requested changes

2024-05-13 09:32 UTC, Wroud commented on server/bundles/io.cloudbeaver.service.admin/schema/service.admin.graphqls
> +
```suggestion
    setUserTeamRole(userId: ID!, teamId: ID!, teamRole: String): Boolean

```

2024-05-13 09:32 UTC, Wroud commented on server/bundles/io.cloudbeaver.service.admin/schema/service.admin.graphqls
> +    grantedUsersInfo: [AdminUserTeamGrantInfo]!
```suggestion
    grantedUsersInfo: [AdminUserTeamGrantInfo!]!
```

2024-05-13 09:32 UTC, Wroud commented on webapp/packages/core-authentication/src/TeamsResource.ts
> +    return team[0].grantedUsersInfo as UserTeamGrantInfo[];
` as UserTeamGrantInfo[];` can be removed after schema fix

2024-05-13 09:32 UTC, Wroud commented on webapp/packages/plugin-authentication-administration/src/Administration/Users/Teams/GrantedUsers/useGrantedUsers.tsx
>        },
seems like we can mutate object in some closer component that have access to it, right now we need to propagate a lot of logic through components

2024-05-13 09:34 UTC, DenisSinelnikov approved these changes

2024-05-14 16:38 UTC, Wroud approved these changes

2024-05-14 17:30 UTC, merged