CB-4706 remove duplicated styles
dbeaver/cloudbeaver pull request #2689
Opened 2024-06-05 16:28 UTC by devnaumov

2024-06-06 07:17 UTC, sergeyteleshev approved these changes

2024-06-12 09:06 UTC, Wroud requested changes

2024-06-12 09:06 UTC, Wroud commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/Table/Columns/ColumnIcon/IconFormatter.module.css
> +  height: 100%;
maybe it's better to set `max-height: 100%` instead to avoid different bugs

2024-06-12 09:06 UTC, Wroud commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/Table/Columns/ColumnSelect/SelectorFormatter.module.css
> +  height: 100%;
same here

2024-06-12 09:06 UTC, Wroud commented on webapp/packages/plugin-react-data-grid/src/DataGrid.tsx
> +export const DataGrid = forwardRef(DataGridInner) as <T>(props: DataGridProps<T> & RefAttributes<DataGridHandle>) => ReturnType<typeof DataGridInner>;
seems completely wrong, whats happening here?

2024-06-12 09:06 UTC, Wroud commented on webapp/packages/plugin-react-data-grid/src/index.ts
> +import { DataGrid } from './DataGrid';
please fix lint warnings

2024-06-12 12:13 UTC, devnaumov commented on webapp/packages/plugin-react-data-grid/src/DataGrid.tsx
> +export const DataGrid = forwardRef(DataGridInner) as <T>(props: DataGridProps<T> & RefAttributes<DataGridHandle>) => ReturnType<typeof DataGridInner>;
?

2024-06-12 12:35 UTC, devnaumov commented on webapp/packages/plugin-object-viewer/src/ObjectPropertiesPage/ObjectPropertyTable/Table/Columns/ColumnIcon/IconFormatter.module.css
> +  height: 100%;
max-height: 100% will not work, please clarify which bugs you are referring to

2024-06-12 14:10 UTC, Wroud approved these changes

2024-06-13 05:03 UTC, merged