Cb 5124 add a notification about the upcoming expiration of the license add to status
dbeaver/cloudbeaver pull request #2733
Opened 2024-06-25 12:58 UTC by DenisSinelnikov

2024-06-26 09:47 UTC, Wroud approved these changes

2024-06-26 11:18 UTC, alexander-skoblikov requested changes

2024-06-26 11:18 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/servlets/CBStatusServlet.java
> +            response.sendError(HttpServletResponse.SC_BAD_REQUEST, "Error additional status info : " + e.getMessage());
we should not send an error in this request

2024-06-28 04:44 UTC, Wroud requested changes

2024-06-28 04:44 UTC, Wroud commented on webapp/packages/core-bootstrap/package.json
> +    "@cloudbeaver/core-website": "^0",
it's not a core it's a plugin

2024-06-28 04:44 UTC, Wroud commented on webapp/packages/core-website/src/WebsiteLinksService.ts
> +}
seems like it's not a service but completely static class, you can make methods also static

2024-06-28 04:44 UTC, Wroud commented on webapp/packages/core-blocks/package.json
> +    "@cloudbeaver/core-dialogs": "^0",
a bit strange that we need `"@cloudbeaver/core-dialogs": "^0",` in core-blocks (because core-dialogs depends on core-blocks)

2024-06-28 04:45 UTC, Wroud commented on webapp/packages/core-bootstrap/package.json
> +    "@cloudbeaver/core-website": "^0",
now i see the problem, that we can't use it in our core-* so leave it as it is for now

2024-06-28 07:29 UTC, Wroud approved these changes

2024-06-28 16:32 UTC, alexander-skoblikov approved these changes

2024-06-28 17:14 UTC, merged