CB-4961 Control files downloading ability
dbeaver/cloudbeaver pull request #2744
Opened 2024-06-26 15:01 UTC by sergeyteleshev

2024-06-27 09:08 UTC, Wroud requested changes

2024-06-27 09:08 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/DataViewerSettingsService.ts
> +        'plugin.data-viewer.disableDownload': 'core.app.dataViewer.disableDownload',
Please remove, aliases needed only for old settings, and it's not relevant for the new one

2024-06-27 14:45 UTC, Wroud requested changes

2024-06-27 14:45 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/DatabaseDataModel/Actions/ResultSet/ResultSetDataContentAction.ts
> +    private readonly dataViewerService: DataViewerService,
this is not responsibility of database data model - it presents only database not hight level API or logic

2024-06-28 04:37 UTC, Wroud approved these changes

2024-06-28 04:38 UTC, Wroud commented
please fix unit tests

2024-06-28 11:21 UTC, sergeyteleshev commented
I removed unit test cause moved the setting to `DataViewerSettingsService`
And cause it is here in cache it shows it as fallen

2024-06-28 11:22 UTC, sergeyteleshev commented
![Снимок экрана 2024-06-28 в 13 22 36](https://github.com/dbeaver/cloudbeaver/assets/26230285/e86e5c68-ee70-4805-963f-da374bfeee85)

2024-06-28 13:14 UTC, devnaumov approved these changes

2024-07-01 12:50 UTC, devnaumov commented on webapp/packages/plugin-data-viewer/src/ValuePanelPresentation/ImageValue/ImageValuePresentation.tsx
> +    function imageOnContextMenuHandler(event: React.MouseEvent<HTMLImageElement>) {
Maybe onImageContextMenu or imageContextMenuHandler

2024-07-01 13:28 UTC, Wroud requested changes

2024-07-01 13:28 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/DataViewerSettingsService.ts
> +  }
please add old alias:
```
      /** @deprecated Use settings instead, will be removed in 23.0.0 */
      createSettingsAliasResolver(this.settingsResolverService, this.settings, { 'plugin.data-export.disabled': 'plugin_data_export.disabled' }),
```
also rename `plugin.data-export.disabled` to `plugin.data-viewer.export.disabled` and add alias to `plugin.data-export.disabled`

2024-07-01 13:28 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/DataViewerSettingsService.ts
> +          description: 'settings_data_editor_disable_data_download_description',
please rename from download to export

2024-07-01 13:28 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/locales/de.ts
> +  ['settings_data_editor_disable_data_download_description', 'Disable exporting of data in Data Viewer for non-admin users'],
please rename to Export

2024-07-01 13:29 UTC, Wroud commented
please fix tests

2024-07-01 14:44 UTC, Wroud approved these changes

2024-07-02 07:22 UTC, Wroud approved these changes

2024-07-02 13:48 UTC, merged