CB-5415. Added full name header for RP
dbeaver/cloudbeaver pull request #2795
Opened 2024-07-22 11:59 UTC by DenisSinelnikov

2024-07-22 15:18 UTC, LonwoLonwo commented on server/bundles/io.cloudbeaver.model/plugin.xml
> +                <property id="fullName" label="Full Name" type="string" description="Full name"/>
```suggestion
                <property id="fullName" label="Full Name" type="string" description="User full name"/>
```

2024-07-22 15:19 UTC, LonwoLonwo commented on server/bundles/io.cloudbeaver.model/plugin.xml
> +                <property id="fullName" label="Full Name" type="string" description="Full name"/>
Optional

2024-07-23 09:39 UTC, alexander-skoblikov requested changes

2024-07-23 09:39 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.security/src/io/cloudbeaver/auth/provider/rp/RPAuthProvider.java
> +            nameBuilder = new StringBuilder(fullName);
this doesn't make sense since we don't support this meta information on UI side, we should use only first/last name

2024-07-24 08:21 UTC, alexander-skoblikov approved these changes

2024-07-25 11:22 UTC, merged