CB-5437 use flex component instead of container
dbeaver/cloudbeaver pull request #2818
Opened 2024-08-01 11:39 UTC by devnaumov

2024-08-02 11:26 UTC, sergeyteleshev approved these changes

2024-08-05 08:23 UTC, Wroud requested changes

2024-08-05 08:23 UTC, Wroud commented on webapp/packages/core-blocks/src/Flex/Flex.tsx
> +      )}
seems like it will be easier to use `s` helper function together with `data-s-*` attribute

2024-08-06 13:00 UTC, Wroud approved these changes

2024-08-07 09:06 UTC, merged