CB-5185 SQL Editor queries highlighting is broken
dbeaver/cloudbeaver pull request #2842
Opened 2024-08-14 12:11 UTC by sergeyteleshev

2024-08-20 04:39 UTC, Wroud approved these changes

2024-08-20 04:39 UTC, Wroud commented on webapp/packages/plugin-sql-editor/src/SqlDataSource/BaseSqlDataSource.ts
> +    this.onSetCursor.execute({ ...this.innerCursorState });
please remove call to onUpdate in that case and use `this.onSetCursor.next(this.onUpdate)`

2024-08-20 09:35 UTC, devnaumov approved these changes

2024-08-21 17:44 UTC, sergeyteleshev commented on webapp/packages/plugin-sql-editor/src/SqlEditor/useSqlEditor.ts
> +        if (this.activeSegment) {
I moved it below cause I don't want to execute the query if selected line of SQL is empty (no query)

also `this.activeSegmentMode.activeSegmentMode` not really works so changed it also to `this.activeSegment`

2024-08-21 17:45 UTC, sergeyteleshev commented on webapp/packages/plugin-sql-editor-new/src/SQLEditor/SQLCodeEditorPanel/useSQLCodeEditorPanel.ts
> +    if (!isScriptChanged) {
this is for the case when we just move the cursor with mouse or keyboard arrows

2024-08-21 17:46 UTC, sergeyteleshev commented on webapp/packages/plugin-sql-editor-new/src/SQLEditor/SQLCodeEditorPanel/useSQLCodeEditorPanel.ts
> +    debounce(() => state.highlightActiveQuery(), 300),
It is more performance and UX-friendly. Now with 120k rows in SQL editor I have almost no lags on my M1 PRO

2024-08-22 06:54 UTC, Wroud requested changes

2024-08-22 06:54 UTC, Wroud commented on webapp/packages/plugin-sql-editor/src/SqlEditor/useSqlEditor.ts
> +        if (this.activeSegment) {
please revert, this will affect other places, please in general don't touch code that work fine (our code related to query execution is working fine so there no need to change anything) when you have problem with different things (highlighting)

2024-08-22 07:04 UTC, Wroud commented
closed in favor of https://github.com/dbeaver/cloudbeaver/pull/2866

2024-08-22 07:04 UTC, closed without merging