CB-5431 Easy config steps are available via url without a license
dbeaver/cloudbeaver pull request #2850
Opened 2024-08-16 16:51 UTC by sergeyteleshev

2024-08-20 05:26 UTC, Wroud requested changes

2024-08-20 05:26 UTC, Wroud commented on webapp/packages/core-administration/src/AdministrationScreen/ConfigurationWizard/ConfigurationWizardService.ts
> +    }
early return, you can move it above isExistingPage and isCurrentStepAvailable consts

2024-08-20 05:26 UTC, Wroud commented on webapp/packages/core-administration/src/AdministrationScreen/ConfigurationWizard/ConfigurationWizardService.ts
> +
seems like `AdministrationScreenService` is better place for this logic (it's already have logic with redirects and access handling)

2024-08-20 05:26 UTC, Wroud commented on webapp/packages/core-administration/src/AdministrationScreen/ConfigurationWizard/ConfigurationWizardService.ts
>      }
do we need this extra loop pass over steps? (we have it below)

2024-08-20 05:28 UTC, Wroud commented on webapp/packages/core-administration/src/AdministrationScreen/ConfigurationWizard/ConfigurationWizardService.ts
> +    }
it is also not needed in case you move it to AdministrationScreenService

2024-08-20 11:23 UTC, Wroud commented on webapp/packages/core-administration/src/AdministrationScreen/ConfigurationWizard/ConfigurationWizardScreenService.ts
> +    }
please use AdministrationScreenService.isConfigurationMode instead

2024-08-22 08:32 UTC, Wroud approved these changes

2024-08-22 09:52 UTC, devnaumov approved these changes

2024-08-26 09:59 UTC, merged