CB-5578 DM: Ability to remove custom certificate
dbeaver/cloudbeaver pull request #2899
Opened 2024-09-05 10:53 UTC by sergeyteleshev

2024-09-09 09:35 UTC, Wroud approved these changes

2024-09-10 15:44 UTC, devnaumov approved these changes

2024-09-16 11:24 UTC, Wroud approved these changes

2024-09-23 13:37 UTC, Wroud requested changes

2024-09-23 13:37 UTC, Wroud commented on webapp/packages/core-utils/src/isValidUrl.ts
> +  return serverUrlPattern.test(value);
file should be renamed also

2024-09-25 13:03 UTC, Wroud requested changes

2024-09-25 13:03 UTC, Wroud commented on webapp/packages/core-blocks/src/ErrorDetailsDialog/ErrorDetailsDialog.tsx
> +        {error.isHtml ? <Iframe srcDoc={translate(error.message)} /> : <div className={s(styles, { message: true })}>{translate(error.message)}</div>}
we sure that we need to translate plain html?

2024-09-25 13:12 UTC, Wroud approved these changes

2024-09-30 08:36 UTC, Wroud approved these changes

2024-10-03 14:51 UTC, Wroud requested changes

2024-10-03 14:51 UTC, Wroud commented on webapp/packages/core-utils/src/removeProtocolFromUrl.ts
> +}
why not use `new URL(url).origin`?
do we really need this helper function?

2024-10-03 15:20 UTC, Wroud approved these changes

2024-10-08 10:02 UTC, Wroud approved these changes

2024-10-08 10:05 UTC, merged