CB-5274. Added new link for download metadata file
dbeaver/cloudbeaver pull request #2900
Opened 2024-09-05 11:27 UTC by DenisSinelnikov

2024-09-09 09:58 UTC, alexander-skoblikov requested changes

2024-09-09 09:58 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.model/src/io/cloudbeaver/auth/SMAuthProviderFederated.java
> +    String getDownloadMetadataFileLink(String id, @NotNull Map<String, Object> providerConfig) throws DBException;
```suggestion
    String getEntityIdLink(String id, @NotNull Map<String, Object> providerConfig) throws DBException;
```

2024-09-09 09:58 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.admin/schema/service.admin.graphqls
> +    downloadMetadataFileLink: String @since(version: "24.2.1")
```suggestion
    enitityIdLink: String @since(version: "24.2.1")
```

2024-09-09 09:58 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.service.auth/schema/service.auth.graphqls
> +    downloadMetadataFileLink: String @since(version: "24.2.1")
```suggestion
    enitityIdLink: String @since(version: "24.2.1")
```

2024-09-09 11:15 UTC, alexander-skoblikov approved these changes

2024-09-10 11:07 UTC, sergeyteleshev approved these changes

2024-09-11 16:10 UTC, merged