CB-4095. Added env variables for configurations parameters
dbeaver/cloudbeaver pull request #2905
Opened 2024-09-09 11:25 UTC by DenisSinelnikov

2024-09-12 11:12 UTC, alexander-skoblikov commented on config/sample-databases/DefaultConfiguration/cloudbeaver.conf
> +        enableSecurityManager: "${CLOUDBEAVER_ENABLE_SECURITY_MANAGER:false}",
we don't need a variable for this parameter right now

2024-09-12 11:12 UTC, alexander-skoblikov commented on config/sample-databases/DefaultConfiguration/cloudbeaver.conf
> +        anonymousUserRole: "${CLOUDBEAVER_ANONYMOUS_USER_ROLE:user}",
anonymousUserRole is deprecated, we should use anonymousUserTeam

2024-09-12 11:12 UTC, alexander-skoblikov commented on config/sample-databases/SQLiteConfiguration/cloudbeaver.conf
> +        anonymousUserRole: "${CLOUDBEAVER_ANONYMOUS_USER_ROLE:user}",
same here

2024-09-12 15:09 UTC, serge-rider requested changes

2024-09-12 15:09 UTC, serge-rider commented on config/sample-databases/DefaultConfiguration/cloudbeaver.conf
> +            dataExportFileSizeLimit: "${CLOUDBEAVER_DATA_EXPORT_FILE_SIZE_LIMIT:10000000}",
LEt's name such variables with prefix. CLOUDBEAVER_RESOURCE_QUOTA_

2024-09-12 15:09 UTC, serge-rider commented on config/sample-databases/SQLiteConfiguration/cloudbeaver.conf
> +        anonymousAccessEnabled: "${CLOUDBEAVER_ANONYMOUS_ACCESS_ENABLED:true}",
Var prefix CLOUDBEAVER_APP_

2024-09-17 16:26 UTC, alexander-skoblikov approved these changes

2024-09-17 16:30 UTC, serge-rider approved these changes

2024-09-17 16:30 UTC, merged

2024-09-25 12:33 UTC, GenLN commented
Those environment variables, can they be disabled? As our custom helm chart deployment with templated connections and configs wont't work if we don't overwrite cloudbeaver.conf in /opt/cloudbeaver location, as image load default one with those ENVs... Image 24.2.0 works great but this patch wouldn't start properly...

Either make all config setup to use ENVs for it, or leave the option to disable/enable those ENVs from image?