Cb 5753 u tests
dbeaver/cloudbeaver pull request #2964
Opened 2024-10-06 19:00 UTC by devnaumov

2024-10-07 11:28 UTC, sergeyteleshev requested changes

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-client-activity/src/ClientActivityService.test.ts
> +    jest.advanceTimersByTime(1000 * 60);
I think it is fine to use `INACTIVE_PERIOD_TIME` const here

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-client-activity/src/ClientActivityService.test.ts
> +    expect(setTimeout).toHaveBeenCalledTimes(2);
would be nice to emulate running time here

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-client-activity/src/ClientActivityService.test.ts
> +    expect(clearTimeout).toHaveBeenCalled();
same here for running time. I suggest to emulate cases like it is actually happening

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-client-activity/src/ClientActivityService.test.ts
> +    expect(onActiveStateChangeSpy).toHaveBeenCalledWith(false);
dont forget to mock Executor also so the test is more moduled. cause if something goes wrong in Executor logic, this test is gonna be fallen as well

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-client-activity/src/ClientActivityService.test.ts
> +    expect(setTimeout).toHaveBeenCalledTimes(2);
you can randomly tick in range from `0` to `INACTIVE_PERIOD_TIME - 1`

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-localization/src/LocalizationService.test.ts
> +    expect(service.supportedLanguages.length).toBeGreaterThan(0);
lets check all of the languages so we know for sure nothing is got lost

I mean like copy paste the array of registred locales here and check that everything is fine

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-localization/src/LocalizationService.test.ts
> +  });
please, split this to 2 different tests:

- should set supported languages
- should set default supported language

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-localization/src/LocalizationService.test.ts
> +    expect(() => service.currentLanguage).toThrowError('No language is available');
this seems weird that getter can throw an error. I suggest to add TODO to refactor this logic somewhen in the `LocalizationService.ts`

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-localization/src/LocalizationService.test.ts
> +  });
please also test multiple arguments

2024-10-07 11:28 UTC, sergeyteleshev commented on webapp/packages/core-localization/src/LocalizationService.test.ts
> +});
I suggest to test also:

- `load();`
- `isLanguageSupported();`

2024-10-14 20:08 UTC, devnaumov commented on webapp/packages/core-localization/src/LocalizationService.test.ts
> +    expect(service.supportedLanguages.length).toBeGreaterThan(0);
Don't understand the need, we only want to check default locale here

2024-10-16 12:52 UTC, sergeyteleshev approved these changes

2024-10-18 05:33 UTC, merged