CB-5712 adds loaders for administration menu items
dbeaver/cloudbeaver pull request #3011
Opened 2024-10-18 12:29 UTC by sergeyteleshev

2024-10-21 10:22 UTC, Wroud commented on webapp/packages/plugin-administration/src/Administration/getLoaders.ts
> +  }
can be simpler: `return [...acc, item.getLoader?.() || []].flat()` (at this point do we need special function for that?)

2024-10-21 10:22 UTC, Wroud commented on webapp/packages/core-authentication/src/AuthProvidersResource.ts
> +
it's better to use `this.preload(this.serverConfigResource, () => undefined)`

2024-10-22 10:20 UTC, Wroud requested changes

2024-10-22 10:20 UTC, Wroud commented on webapp/packages/core-authentication/src/AuthProvidersResource.ts
> +    this.preloadResource(this.serverConfigResource, () => undefined);
proloadResource must be executed in constructor and only once

2024-10-23 08:02 UTC, Wroud requested changes

2024-10-23 08:02 UTC, Wroud commented on webapp/packages/core-authentication/src/AuthProvidersResource.ts
>        serverConfigResource,
sync already preloads resource

2024-10-23 08:02 UTC, Wroud commented on webapp/packages/core-authentication/src/AuthProvidersResource.ts
>        serverConfigResource,
so you don't need to add `this.preloadResource(this.serverConfigResource, () => undefined);` or load `serverConfigResource` in loader manually

2024-10-23 08:22 UTC, Wroud approved these changes

2024-10-23 09:34 UTC, devnaumov approved these changes

2024-10-24 08:04 UTC, merged