Cb 5819 administration tables redesign
dbeaver/cloudbeaver pull request #3033
Opened 2024-10-27 21:14 UTC by devnaumov

2024-10-28 15:57 UTC, Wroud requested changes

2024-10-28 15:57 UTC, Wroud commented on webapp/packages/core-blocks/src/Containers/GroupTitle.tsx
> +  );
please remove, use composition instead, another question we have `GroupClose` component what is wrong with it?

2024-10-28 18:25 UTC, sergeyteleshev commented on webapp/packages/plugin-authentication-administration/src/Administration/Users/UsersTable/UsersTableOptionsPanelService.ts
> +}
I can see that this is exact same class as `TeamTableOptionsPanelService`. Do you think we can do something about logic duplication?

2024-10-28 22:14 UTC, sergeyteleshev approved these changes

2024-10-29 06:41 UTC, Wroud approved these changes

2024-10-29 19:43 UTC, merged