CB-5878 add title for inline editor button
dbeaver/cloudbeaver pull request #3042
Opened 2024-11-04 16:40 UTC by SychevAndrey

2024-11-04 16:52 UTC, devnaumov requested changes

2024-11-04 16:52 UTC, devnaumov commented on webapp/packages/core-localization/src/locales/en.ts
> +  ['ui_reject', 'Reject'],
We probably could use just ui_cancel?

2024-11-04 17:01 UTC, SychevAndrey commented on webapp/packages/core-localization/src/locales/en.ts
> +  ['ui_reject', 'Reject'],
We discussed it with @Wroud and he was for adding Reject option. Anyway there is no cancel token in locales, there is only `processing_cancel`, so we need to add either Reject or Cancel

2024-11-04 17:29 UTC, devnaumov approved these changes

2024-11-04 17:29 UTC, devnaumov commented on webapp/packages/core-localization/src/locales/en.ts
> +  ['ui_reject', 'Reject'],
Then we need to change ru locale to "Отклонить"

2024-11-05 09:35 UTC, SychevAndrey commented on webapp/packages/core-localization/src/locales/en.ts
> +  ['ui_reject', 'Reject'],
Personally I like more cancel option with "Отменить" translation. Can we discuss together and decide?

2024-11-05 09:38 UTC, sergeyteleshev approved these changes

2024-11-06 11:41 UTC, merged