CB-5891 User - error after disabling and deleting
dbeaver/cloudbeaver pull request #3056
Opened 2024-11-06 21:38 UTC by sergeyteleshev

2024-11-07 10:36 UTC, Wroud requested changes

2024-11-07 10:36 UTC, Wroud commented on webapp/packages/plugin-authentication-administration/src/Administration/Users/UserForm/AdministrationUserForm.tsx
> +  }
seems like we need to create `disable` method in the form part and use it to disable user and sync form:
(pseudocode)
```
this.state.enabled = false;
await this.save()
```

2024-11-07 13:14 UTC, Wroud requested changes

2024-11-07 13:14 UTC, Wroud commented on webapp/packages/plugin-authentication-administration/src/Administration/Users/UserForm/Info/UserFormInfoPart.ts
> +    await this.saveChanges();
You need to call `save` to handle update and error handling logic (for example, if the user made some changes that will not pass validation, calling saveChanges directly will skip this logic, and it also will make it possible to run multiple concurrent save requests to the backend

2024-11-08 11:25 UTC, devnaumov approved these changes

2024-11-11 11:26 UTC, Wroud approved these changes

2024-11-11 11:27 UTC, merged