CB-5016 add disable import option to global config
dbeaver/cloudbeaver pull request #3058
Opened 2024-11-07 11:58 UTC by SychevAndrey

2024-11-07 13:10 UTC, Wroud submitted a review, later dismissed

2024-11-07 13:10 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/DataViewerSettingsService.ts
> +        },
please move this changes to the `DataImportSettingsService`

2024-11-07 16:36 UTC, devnaumov requested changes

2024-11-07 16:36 UTC, devnaumov commented on webapp/packages/plugin-data-viewer/src/locales/de.ts
> +  ['settings_data_editor_disable_data_import_name', 'Disable Import'],
Seems like this token is used only in plugin-data-import, I suggest to move it there

2024-11-07 19:17 UTC, sergeyteleshev requested changes

2024-11-07 19:17 UTC, sergeyteleshev commented on webapp/packages/plugin-data-import/src/locales/ru.ts
> +  ['plugin_data_import_disable_data_import_description', 'Отключить загрузку данных для пользователей без прав администратора'],
feature is called `"Импорт данных"`
so this text goes to: `"Отключить импорт данных"` and `"Отключить импорт данных для пользователей без прав администратора"`

2024-11-08 09:54 UTC, sergeyteleshev approved these changes

2024-11-08 11:24 UTC, devnaumov approved these changes

2024-11-12 17:33 UTC, merged