Cb 5584 provide more information in the debug log for auditing
dbeaver/cloudbeaver pull request #3061
Opened 2024-11-07 17:08 UTC by DenisSinelnikov

2024-11-08 14:11 UTC, alexander-skoblikov commented on server/bundles/io.cloudbeaver.server/plugin.xml
> +            <property id="log.on.show.variables" label="Show all variables in log"
strange naming

2024-11-08 17:06 UTC, serge-rider requested changes

2024-11-08 17:06 UTC, serge-rider commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/graphql/GraphQLLoggerUtil.java
> +        if (session != null) {
request.getsession may be null

2024-11-08 17:06 UTC, serge-rider commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/graphql/GraphQLLoggerUtil.java
> +        if (CBPlatform.getInstance().getPreferenceStore().getBoolean("log.debug") && variables != null) {
Why use pref store for that? Where `log.debug` is declared elsewhere?

2024-11-08 17:06 UTC, serge-rider commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/graphql/GraphQLProhibitedVariables.java
> +    PASSWORD("password"),
It don't think that global enum will work. We need some explicit annotations for parameters which we do not want to log (for example as comments).
However we need to move log invocation into WebExecutionStrategy to get information about GQL endpoint.

If this is too complicated then we can keep it as is for now. In this case add "credentials" and "username" too. 
However I don't understand why we need enum but simple Set<String>

2024-11-11 15:42 UTC, DenisSinelnikov commented on server/bundles/io.cloudbeaver.server/src/io/cloudbeaver/server/graphql/GraphQLProhibitedVariables.java
> +    PASSWORD("password"),
let's leave Set for now, added additional parameters, let's start a task on improve with annotations, need more time for realization

2024-11-21 15:52 UTC, merged