CB-5933 Connection state is not synchronized with other resources triggering connection state
dbeaver/cloudbeaver pull request #3119
Opened 2024-12-04 17:55 UTC by sergeyteleshev

2024-12-06 14:33 UTC, Wroud requested changes

2024-12-06 14:33 UTC, Wroud commented on webapp/packages/core-connections/src/ConnectionInfoResource.ts
> +        }
please use isConnecting (you then can make only one if)

2024-12-06 14:33 UTC, Wroud commented on webapp/packages/core-connections/src/ConnectionInfoResource.ts
> +        }
same here

2024-12-06 14:49 UTC, Wroud approved these changes

2024-12-09 12:18 UTC, yagudin10 approved these changes

2024-12-12 10:27 UTC, merged