Cb 5988 plugin template
dbeaver/cloudbeaver pull request #3136
Opened 2024-12-13 11:16 UTC by devnaumov

2024-12-16 13:00 UTC, Wroud requested changes, later dismissed

2024-12-16 13:00 UTC, Wroud commented on webapp/packages/core-cli/bin/add-plugin.js
> +  createPrompter: () => require('enquirer'),
please add enquirer dependency to the package.json

2024-12-16 13:00 UTC, Wroud commented on webapp/packages/core-cli/_templates/plugin/new/tsconfig.json.ejs.t
> +    }
will not work in ee

2024-12-16 13:00 UTC, Wroud commented on webapp/packages/core-cli/_templates/plugin/new/package.json.ejs.t
> +  },
should have core-cli and typescript dev dependencies

2024-12-16 13:00 UTC, Wroud commented on webapp/packages/core-cli/_templates/plugin/new/manifest.ts.ejs.t
> +export const <%= h.changeCase.camel(name) %>: PluginManifest = {
please add Manifest suffix

2024-12-16 13:00 UTC, Wroud commented on webapp/packages/core-cli/_templates/plugin/new/service.ts.ejs.t
> +export class <%= h.changeCase.pascal(name) %>Service extends Bootstrap {
please use Bootstrap suffix

2024-12-23 20:22 UTC, devnaumov commented on webapp/packages/core-cli/_templates/plugin/new/package.json.ejs.t
> +  },
I think core-cli would be extra here? Seems like It will not pass validate-references script

2024-12-24 09:33 UTC, sergeyteleshev approved these changes

2024-12-24 13:20 UTC, merged