CB-3753-1809-fr-add-field-hints-in-the-filter-field
dbeaver/cloudbeaver pull request #3151
Opened 2024-12-23 13:46 UTC by sergeyteleshev

2024-12-26 15:54 UTC, SychevAndrey approved these changes
👍🏻

2024-12-26 15:54 UTC, SychevAndrey commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +  filter?: (suggestion: InputAutocompleteProposal, lastWord?: string) => boolean;
I believe `predicate` is more descriptive word for that prop, then filter.

2024-12-26 15:54 UTC, SychevAndrey commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +        if (!isNotNullDefined(words) || !isNotNullDefined(cursorPosition) || !isNotNullDefined(this.currentWord)) {
Do we need to check words and cursor here if currentWord getter should return falsy value if there is no words or cursorPosition?

2024-12-26 15:54 UTC, SychevAndrey commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +          })
```suggestion
const isMatch = () => {
  const { matchStrategy, currentWord } = this;

  if (!isNotNullDefined(currentWord)) {
    return false;
  }

  const matchFunctions: { [key: InputAutocompleteStrategy]: (value: string) => boolean } = {
    startsWith: value => value.startsWith(currentWord),
    contains: value => value.includes(currentWord),
    fuzzy: value => isFuzzySearchable(currentWord, value),
  };

  return values.some(matchFunctions[matchStrategy]);
};
```


Maybe like that? And we checked thus.currentWord just above, so maybe we can skip this check:
```
 if (!isNotNullDefined(currentWord)) {
    return false;
  }
```

2024-12-27 11:14 UTC, devnaumov requested changes

2024-12-27 11:14 UTC, devnaumov commented on webapp/packages/core-utils/src/isFuzzySearchable.ts
> +export function isFuzzySearchable(pattern: string, text: string): boolean {
Maybe we should use fuzzy library?

2024-12-27 11:14 UTC, devnaumov commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.tsx
> +  return (
We should probably use combobox component as its based on the input and supports search

2025-01-13 20:55 UTC, sergeyteleshev commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.tsx
> +  return (
seems redundant for me. we should implement it once we migrate from reakit to something better. cause for now matching our combobox + reakit menus with our wrapper over it `Menu.tsx` seems like a nightmare

2025-01-13 20:57 UTC, sergeyteleshev commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +  filter?: (suggestion: InputAutocompleteProposal, lastWord?: string) => boolean;
done

2025-01-13 20:57 UTC, sergeyteleshev commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +        if (!isNotNullDefined(words) || !isNotNullDefined(cursorPosition) || !isNotNullDefined(this.currentWord)) {
done

2025-01-13 20:57 UTC, sergeyteleshev commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +          })
done

2025-01-14 11:40 UTC, SychevAndrey approved these changes

2025-01-14 12:11 UTC, Wroud requested changes

2025-01-14 12:11 UTC, Wroud commented on webapp/packages/core-blocks/package.json
> +    "fuse.js": "^7",
What options do we have besides this library? (I'm curious because it's not actively maintained; maybe other options have more active support)

2025-01-14 12:11 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +  }, INPUT_DELAY);
Without memo this function will not work as expected in case its call trigger component re-render

2025-01-14 12:11 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.module.css
> +}
please reuse `BaseDropdownStyles` instead

2025-01-14 12:11 UTC, Wroud commented on webapp/packages/core-blocks/src/Menu/Menu.tsx
> +        document.body.appendChild(span);
Please use the menu anchor (invisible menu trigger / button) instead (you can position it as you need)

2025-01-14 12:11 UTC, Wroud commented on webapp/packages/core-ui/src/InlineEditor/InlineEditor.tsx
> +  autoCompleteProposals?: InputAutocompleteProposal[];
please do not extend `InlineEditor` functionality cuz its deprecated and we want to use our base controls instead

2025-01-14 12:11 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/TableViewer/TableHeader/useWhereFilter.ts
>    readonly constraints: DatabaseDataConstraintAction | null;
please abstract where filter from columns or structure of the data

2025-01-20 08:40 UTC, Wroud requested changes

2025-01-20 08:40 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.tsx
> +  });
please move this hook outside from the component, so you can use it and use input ref in the same component

2025-01-20 08:40 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.tsx
> +  }, [inputRef.current]);
this all can be part of the hook probably

2025-01-20 08:40 UTC, Wroud commented on webapp/packages/core-blocks/src/Menu/Menu.tsx
> +  contextInputRef?: React.RefObject<HTMLInputElement | HTMLTextAreaElement>;
looks like it's not a part of the menu

2025-01-22 04:22 UTC, Wroud requested changes

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +}
strange function

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  const searchInstance = useRef(createSearchInstance<T>(minisearchOptions));
it will create new instance every render, the better solution is to use `useState` or:
```
const searchInstance = useRef(null);
if (searchInstance === null) {
  searchInstance.current = new MiniSearch<T>(options);
}
```

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  }, [sourceProposals]);
1. why we re-create instance?
2. why we use `useEffect`?

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  }, new Set<string>());
it seems that logic is overcomplicated in this hook and can be simplifyed:
```
export function useFuzzySearch<T extends object>({ sourceProposals, ...options }: UseSearchProps<T>) {
  const minisearchRef = useRef(null);
  const currentOptions = useRef({});

  if (minisearchRef.current === null || !isObjectEqual(currentOptions.current, options)) {
    minisearchRef.current = new Minisearch(options);
    currentOptions.current = options;
  }
  
  useMemo(() => autorun(() => { // here we ensure that mutable props from mobx object will be traced correctly
    minisearchRef.current.removeAll();
    minisearchRef.current.addAll(sourceProposals);
  }), [sourceProposals]) // possible we can tune how we determine changes in sourceProposals (we can write our own logic for example with use of isArrayEqual)
  
  ....
```

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  }, new Set<string>());
i'm not sure that we need to index all fields passed  as proposals it's better to declare fields manually with type: `fields: Array<keyof T>`

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  const minisearchOptions = { ...options };
in case this hook is specific binding of minisearch for react, then we probably want to keep original interface as much as possible

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +  id: string;
i suggest to remove this 'id' fields because:
1. it's not in use
2. it's just a "always" random string

2025-01-22 04:22 UTC, Wroud commented on webapp/packages/core-blocks/src/Menu/useContextMenuPosition.ts
> +  } | null;
I don't personally like inlining public types cuz it's impossible to use them if needed only with `SomeType['someKey']`

2025-01-22 04:24 UTC, Wroud commented
please take a look at this: https://github.com/lucaong/react-minisearch
and this: https://github.com/lucaong/react-minisearch/issues/38#issuecomment-1619129761

2025-01-24 07:46 UTC, Wroud requested changes

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.tsx
> +  }, [inputRef.current]);
`React.RefObject` can't be used this way because:
1. it's passed as a component property
2. it's mutated by react and will not cause child component (this component) to re-render when the `current` changed

if you need some logic related to some input ref please place this logic in some hook and use this hook in the same component that passes ref to input to avoid synchronization bugs

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +      selectionStart: inputRef.current?.selectionStart ?? null,
this initial value will be incorrect because at the moment of initialization there may be no `current` object yet

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  fields: string[];
why not to use `Array<keyof T>` for `fields`?

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  );
I will suggest removing this part for now. We may implement it later when we have different engines (if we have them), and we can't be sure that implementation will be like this if we imagine 3-4 engines written similarly. Then it may be performance issues (right now, we indexing every re-render miniseach even if the engine will be some other one)

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/core-blocks/src/useFuzzySearch.ts
> +  });
this way documents are already added on render, so please replace `sourceProposals` with `[]` or remove the `useMemo` block

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/core-blocks/src/useSearch.ts
> +        }
Why do we use early return here? Is it expected that with a `fuzzy` strategy, `setSeach` will not change the `search` state?

2025-01-24 07:46 UTC, Wroud commented on webapp/packages/plugin-data-viewer/src/TableViewer/TableHeader/useTableViewerHeaderData.ts
> +        );
please remove extra fields

2025-01-27 11:56 UTC, Wroud approved these changes

2025-01-27 11:56 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/InputAutocompletionMenu.tsx
> +  }));
getComputed will not help cuz function always returns new object (getComputed works if you can return stable value, for example for primitives)

2025-01-27 11:56 UTC, Wroud commented on webapp/packages/core-blocks/src/FormControls/useInputAutocomplete.ts
> +  }, []);
This will lead to unexpected behavior if the input is unmounted because the hook is executed only once at the first render. I will suggest to remove deps ([]) to run this hook every re-render

2025-01-27 14:37 UTC, devnaumov approved these changes

2025-01-28 17:08 UTC, merged