Add it translation +  add translation keys for navigation tree 'no co…
dbeaver/cloudbeaver pull request #833
Opened 2022-05-16 14:04 UTC by fracasso

Add it translation +  add translation keys for navigation tree 'no connection'

2022-06-23 10:37 UTC, devnaumov requested changes

2022-06-23 10:37 UTC, devnaumov commented on webapp/packages/core-app/src/NavigationTree/NavigationTree.tsx
> +              {translate('ui_no_connection')}<br />
Better use one token and break it with a \n symbol.

2022-06-23 10:37 UTC, devnaumov commented on webapp/packages/core-localization/src/locales/en.ts
> +  ['ui_no_connection', "No Connections."],
It's not a UI specific so better move it to the core-app package and name the token something like app_navigationTree_no_connections_placeholder

2022-06-23 10:37 UTC, devnaumov commented on webapp/packages/core-app/src/NavigationTree/NavigationTree.tsx
> +
One indent

2022-06-23 10:47 UTC, devnaumov commented
Hi @fracasso! Thanks for your contribution. We left some comments that need to be fixed before the merge.

2024-03-05 17:55 UTC, LonwoLonwo commented
Hello @fracasso 

Thanks for your contribution! 
Sorry that we missed it.
Unfortunately, I can't review your localization part because it is under all other CloudBeaver Team commits.
So, please create a new PR on the latest devel branch. And we will review it in time.
I need to close this PR due to its unreadability.

2024-03-05 17:55 UTC, closed without merging